<template>
  <div
    class="
      sm:py-10
      lg:py-9
      xl:py-9
      2xl:py-9
      py-12
      px-4
      sm:px-14
      md:px-14
      lg:px-16
      xl:px-24
      2xl:px-24
      space-y-4
    "
  >
    <h1
      class="
        font-extrabold
        text-2xl
        underline
        tracking-wide
        text-monokai-default
      "
    >
      <slot name="header"></slot>
    </h1>
    <div
      style="line-height: 1.8"
      class="
        break-words
        text-sm
        sm:text-md
        md:text-md
        xl:text-lg
        2xl:text-xl
        text-monokai-default
      "
    >
      <slot name="content"></slot>
    </div>
  </div>
</template>
